name: Build and Push Docker Images

on:
  workflow_call:
    inputs:
      environment:
        description: 'environment name'
        required: true
        type: string  
      repository:
        required: true
        type: string 
      docker_path:
        required: false
        default: .
        type: string   
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      BUILD_ARGS:
        required: false
    outputs:
      tag:
        description: The image tag
        value: ${{ jobs.build.outputs.outcome }}
jobs:
  check_org:
    runs-on: ubuntu-latest
    steps:
      - name: Check the calling organization
        if: ${{ github.repository_owner != 'onrunning' }}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('This reusable workflow can only be used by My Org.')
  build:
    outputs:
      outcome: ${{ steps.set-tag.outputs.image-tag }}
    name: Build and Publish Image
    runs-on: ubuntu-latest
    needs: check_org
    
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and Tag
      id: set-tag
      env:
        ECR_REPOSITORY: ${{ inputs.repository }}
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ inputs.environment }}

      run: |
        echo SHORT_SHA=$(git rev-parse --short HEAD) >> $GITHUB_OUTPUT
        docker build ${{ secrets.BUILD_ARGS }} -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG-$SHORT_SHA ${{ inputs.docker_path }}
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG-$SHORT_SH
        echo "image-tag=$IMAGE_TAG-$SHORT_SH" >> $GITHUB_OUTPUT
    