name: Deploy via ArgoCD
on:
  workflow_call:
    inputs:
      image-tag:
        required: true
        type: string
jobs:
  Deploy:
    name: Deploy to ArgoCD
    runs-on: ubuntu-latest
    steps:
    - name: Echo tag
      run: |
        echo "${{ inputs.image-tag }}"
   