name: Deploy via ArgoCD
on:
  workflow_call:
    inputs:
      image-tag:
        required: true
        type: string
      ecr_repository:
        required: true
        type: string
      file_path:
        required: true
        type: string
    secrets:
      GITOPS_USER:
        required: true
      GITOPS_TOKEN:
        required: true
jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: update argocd app
      run: |
        git clone https://${{ secrets.GITOPS_USER }}:${{ secrets.GITOPS_TOKEN }}@github.com/onrunning/it-argocd-manifest.git
        git config --global user.email "gitops@on-running"
        git config --global user.name  "gitops"
        echo "Deploying application with image ${{ inputs.image-tag }}"
        sed -i "s/${{ inputs.ecr_repository }}:.*/${{ inputs.ecr_repository }}:${{ inputs.image-tag }}/gI" it-argocd-manifest/apps/${{ inputs.file_path }}
        cd it-argocd-manifest/apps/
        git pull
        git add .
        git commit -m "update image tag"
        git push origin main